#!/bin/bash
LAST_COMMIT="$(git log --pretty=format:"%h;%cd;%an<%ae>;%s" -1)"
URL=$(../jandi.config)
HEADER="Accept: application/vnd.tosslab.jandi-v2+json"
HEADER_TYPE="Content-Type: application/json"
in=$LAST_COMMIT
IFS=';'
ARRAY=($in)
HASH=${ARRAY[0]}
DATE=${ARRAY[1]}
AUTHOR=${ARRAY[2]}
TITLE=${ARRAY[3]}
BODY="{\"body\":\"[[${HASH}]](http://url_to_text) 새로운 커밋이 추가되었습니다. -${AUTHOR}\",\"connectColor\":\"#FAC11B\",\"connectInfo\":[{\"title\":\"${TITLE}\",\"description\":\"${DATE}\"}]}"
echo "$BODY"
curl -X POST "${URL}" -H "${HEADER}" -H "${HEADER_TYPE}" --data-binary "${BODY}"
